# dataset
dataset: GoRecDial
tokenize: nltk
# dataloader
context_truncate: 256
response_truncate: 30
scale: 1
# model
model: KBRD
token_emb_dim: 300
kg_emb_dim: 128
num_bases: 8
n_heads: 2
n_layers: 2
ffn_size: 300
dropout: 0.1
attention_dropout: 0.0
relu_dropout: 0.1
learn_positional_embeddings: false
embeddings_scale: true
reduction: false
n_positions: 512
user_proj_dim: 512
# optim
rec:
  epoch: 5
  batch_size: 2048
  optimizer:
    name: Adam
    lr: !!float 5e-4
conv:
  epoch: 5
  batch_size: 256
  optimizer:
    name: Adam
    lr: !!float 5e-4
  lr_scheduler:
    name: ReduceLROnPlateau
    patience: 3
    factor: 0.5
  gradient_clip: 0.1
  early_stop: true
  stop_mode: min
  impatience: 3
