# dataset
dataset: Inspired
tokenize: nltk
# dataloader
context_truncate: 1024
response_truncate: 256
scale: 1
# model
model: KBRD
token_emb_dim: 300
kg_emb_dim: 128
num_bases: 8
n_heads: 2
n_layers: 2
ffn_size: 300
dropout: 0.05
attention_dropout: 0.0
relu_dropout: 0.05
learn_positional_embeddings: false
embeddings_scale: true
reduction: false
n_positions: 1024
user_proj_dim: 512
# optim
rec:
  epoch: 8
  batch_size: 1024
  optimizer:
    name: Adam
    lr: !!float 5e-4
conv:
  epoch: 3
  batch_size: 128
  early_stop: True
  stop_mode: min
  optimizer:
    name: Adam
    lr: !!float 5e-4
  lr_scheduler:
    name: ReduceLROnPlateau
    patience: 3
    factor: 0.2
